# Generated by Django 5.0.6 on 2025-07-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_alter_pastquestion_id_alter_prediction_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pastquestion',
            unique_together={('subject', 'year', 'paper_number')},
        ),
    ]
