# Generated by Django 5.0.6 on 2025-07-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_alter_pastquestion_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pastquestion',
            unique_together=set(),
        ),
    ]
