# Generated by Django 5.0.6 on 2025-07-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_alter_pastquestion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastquestion',
            name='topic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
