# Generated by Django 5.0.6 on 2025-07-29 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_rename_predicted_questions_prediction_predicted_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTopicOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.TextField()),
                ('year', models.IntegerField()),
                ('paper_number', models.IntegerField()),
                ('count', models.IntegerField(default=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.subject')),
            ],
            options={
                'unique_together': {('subject', 'topic', 'year', 'paper_number')},
            },
        ),
    ]
