# Generated by Django 5.0.6 on 2025-07-30 12:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0007_papertopicoccurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTopicSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('paper_number', models.IntegerField()),
                ('topics', models.JSONField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.subject')),
            ],
            options={
                'unique_together': {('subject', 'year', 'paper_number')},
            },
        ),
        migrations.DeleteModel(
            name='PaperTopicOccurrence',
        ),
    ]
